server:
  port: ${PORT:8000}
spring:
  application:
    name: usuario
  datasource:
    username: root
    password: 123456
    url: ${DATASOURCE:jdbc:mariadb://localhost:43306/usuario}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
